version: '3'
services:
  first:
    image: btcd:latest
    command: [
      "/app/btcd",
      "--testnet",
      "--addrindex",
      # "--generate",
      "--nodnsseed",
      "--miningaddr=dagtest:qrm4zaetvny2yuh4wudf8y43fd20lunkxs8quragg8",
      "--rpcuser=user",
      "--rpcpass=pass",
      "--rpclisten=0.0.0.0:18334",
      "--rpccert=/app/rpc.cert",
      "--rpckey=/app/rpc.key"
    ]
    ports: ["18334:18334"]
  second:
    image: btcd:latest
    links: ["first"]
    command: [
      "/app/btcd",
      "--testnet",
      "--addrindex",
      "--connect=first",
      "--rpcuser=user",
      "--rpcpass=pass",
      "--miningaddr=dagtest:qrm4zaetvny2yuh4wudf8y43fd20lunkxs8quragg8",
      "--rpclisten=0.0.0.0:18334",
      "--rpccert=/app/rpc.cert",
      "--rpckey=/app/rpc.key"
    ]
    ports: ["18335:18334"]
