version: '3'
services:
  first:
    image: btcd:latest
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    command: [
      "./btcd",
      "--devnet",
      "--addrindex",
      "--generate",
      "--nodnsseed",
      "--miningaddr=dagtest:qzm8w9w0x7lctyxrwh86909wttphm4f84s5wmxn622",
      "--rpcuser=user",
      "--rpcpass=pass",
      "--rpclisten=0.0.0.0:18334",
      "--rpccert=/go/src/github.com/daglabs/btcd/docker/rpc.cert",
      "--rpckey=/go/src/github.com/daglabs/btcd/docker/rpc.key"
    ]
    ports: ["18334:18334"]

  second:
    image: btcd:latest
    links: ["first"]
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    command: [
      "./btcd",
      "--devnet",
      "--generate",
      "--addrindex",
      "--connect=first",
      "--rpcuser=user",
      "--rpcpass=pass",
      "--miningaddr=dagtest:qzm8w9w0x7lctyxrwh86909wttphm4f84s5wmxn622",
      "--rpclisten=0.0.0.0:18334",
      "--rpccert=/go/src/github.com/daglabs/btcd/docker/rpc.cert",
      "--rpckey=/go/src/github.com/daglabs/btcd/docker/rpc.key"
    ]
    ports: ["18335:18334"]

  second-debug:
    image: btcd:latest
    links: ["first"]
    security_opt:
      - apparmor=unconfined
    cap_add:
      - SYS_PTRACE
    command: [
      "dlv",
      "--listen=:40000",
      "--api-version=2",
      "--headless=true",
      "exec",
      "./btcd",
      "--",
      # here starts btcd parameters
      "--devnet",
      "--generate",
      "--addrindex",
      "--connect=first",
      "--rpcuser=user",
      "--rpcpass=pass",
      "--miningaddr=dagtest:qzm8w9w0x7lctyxrwh86909wttphm4f84s5wmxn622",
      "--rpclisten=0.0.0.0:18334",
      "--rpccert=/go/src/github.com/daglabs/btcd/docker/rpc.cert",
      "--rpckey=/go/src/github.com/daglabs/btcd/docker/rpc.key"
    ]
    ports: ["18335:18334", "40000:40000"]
