name: Pull Request Comment Trigger
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Example
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
      - run: echo "Hello World"